In [9]:
# EDA
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# ML
from sklearn.decomposition import PCA
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import numpy as np

In [5]:
df_countries = pd.read_csv('./dataset/dataset_paises.csv', sep=';', decimal=',')

### Carga de Dados

In [11]:
df_countries.info()

<class 'pandas.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          165 non-null    str
 1   child_mort       165 non-null    float64
 2   exports          165 non-null    float64
 3   health           165 non-null    float64
 4   imports          165 non-null    float64
 5   income           165 non-null    int64
 6   inflation        165 non-null    float64
 7   life_expec       165 non-null    float64
 8   total_fer        165 non-null    float64
 9   gdpp             165 non-null    int64
 10  income_category  165 non-null    str
dtypes: float64(7), int64(2), str(2)
memory usage: 14.3 KB

In [7]:
df_countries.head(10)

               country  child_mort  ...   gdpp      income_category
0          Afghanistan        90.2  ...    553           Low income
1              Albania        16.6  ...   4090  Upper middle income
2              Algeria        27.3  ...   4460  Lower middle income
3               Angola       119.0  ...   3530  Lower middle income
4  Antigua and Barbuda        10.3  ...  12200          High income
5            Argentina        14.5  ...  10300  Upper middle income
6              Armenia        18.1  ...   3220  Upper middle income
7            Australia         4.8  ...  51900          High income
8              Austria         4.3  ...  46900          High income
9           Azerbaijan        39.2  ...   5840  Upper middle income

[10 rows x 11 columns]

In [8]:
df_countries.tail(10)

                  country  child_mort  ...   gdpp      income_category
155               Ukraine        11.7  ...   2970  Lower middle income
156  United Arab Emirates         8.6  ...  35000          High income
157        United Kingdom         5.2  ...  38900          High income
158         United States         7.3  ...  48400          High income
159               Uruguay        10.6  ...  11900          High income
160            Uzbekistan        36.3  ...   1380  Lower middle income
161               Vanuatu        29.2  ...   2970  Lower middle income
162               Vietnam        23.3  ...   1310  Lower middle income
163                 Yemen        56.3  ...   1310           Low income
164                Zambia        83.1  ...   1460  Lower middle income

[10 rows x 11 columns]

### EDA